# Generated by Django 2.2.4 on 2019-08-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reset_id',
            field=models.CharField(max_length=8),
        ),
    ]
