# Generated by Django 2.2.4 on 2019-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0002_auto_20190827_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reset_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=8),
        ),
    ]
