# Generated by Django 2.2.3 on 2019-09-03 23:45

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0004_remove_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
