# Generated by Django 2.2.3 on 2019-09-04 00:08

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0006_auto_20190903_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', min_length=4, primary_key=True, serialize=False),
        ),
    ]
