# Generated by Django 2.2.8 on 2020-01-03 17:11

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0008_auto_20190903_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_length=3, primary_key=True, serialize=False),
        ),
    ]
