# Generated by Django 2.2.8 on 2020-01-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicky', '0010_room_can_see_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_choices',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
